/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Agency = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const AgencySelection = IDL.Record({
  'isCustom' : IDL.Bool,
  'selectedAgency' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'lastPlayed' : IDL.Opt(IDL.Int),
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCustomAgency' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getAllAgencies' : IDL.Func([], [IDL.Vec(Agency)], ['query']),
  'getCallerAgencySelection' : IDL.Func(
      [],
      [IDL.Opt(AgencySelection)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'selectPredefinedAgency' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Agency = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const AgencySelection = IDL.Record({
    'isCustom' : IDL.Bool,
    'selectedAgency' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'lastPlayed' : IDL.Opt(IDL.Int),
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCustomAgency' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getAllAgencies' : IDL.Func([], [IDL.Vec(Agency)], ['query']),
    'getCallerAgencySelection' : IDL.Func(
        [],
        [IDL.Opt(AgencySelection)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'selectPredefinedAgency' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };